### PR TITLE
Switch sending metrics to a different Influx server

### PR DESCRIPTION
**Pull request by harnash**
ping: @Wikia/platform-team

### CODE REVIEW

**Review by Grunny — APPROVED** [review]

**Review by tmszdmsk — CHANGES_REQUESTED** [review]
why this pr has so many commits? :)

**Comment by tmszdmsk** [comment]
+ we have to coordinate this change with changing kapacitor config.

**Comment by sqreek** [comment]
app-metrics-db exists only in sjc prod
Our alert tickets will rise on others env/dc

**Comment by harnash** [comment]
@sqreek that is not a problem. We do have one NSQ queue for prod and dev so alerts from both envs already go into one (SJC) database. They are properly tagged with `cluster_name` and `data_center` so we can filter them out if needed.

**Comment by sqreek** [comment]
https://github.com/Wikia/chef-repo/pull/14613

**Comment by tmszdmsk** [comment]
Since kapacitor is prepared for handling data from `app-metrics-db` I will merge it and push to prod.

**Review by tmszdmsk — APPROVED** [review]

**Pull request merged**
